services:
  db:
    image: postgres:17
    container_name: aepeti-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: aepeti-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_SECURITY_USER: ${SPRING_SECURITY_USER}
      SPRING_SECURITY_PASSWORD: ${SPRING_SECURITY_PASSWORD}
    depends_on:
      - db
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false

  frontend:
    build: ./frontend
    container_name: aepeti-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --poll 2000"

volumes:
  db_data:
